// ProjectManagementApp_Angular/src/app/components/home/home.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
    selector: 'app-home',
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.scss']
})
export class HomeComponent {
    protected noProject: boolean = true;

    constructor(private router: Router) {}

    ngOnInit() {}

    navigate() {
        this.router.navigate([this.noProject ? '/create-project' : '/my-projects']);
    }
}

<div class="text-center">
    <img class="object-contain mx-auto mt-12 mb-4"
        [ngClass]="noProject ? 'w-1/2' : 'w-1/3'"
        [src]="noProject ? 'assets/images/notfound.svg' : 'assets/images/allprojects.jpg'" />
    <h1 class="text-gray-500 font-bold text-xl">
        {{ noProject ? 'No Project Found. Please create a new Project' : 'Check all you projects created' }} 
    </h1>
    <button (click)="navigate()" type="button" class="w-36 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium 
        rounded-lg text-sm px-5 py-2.5 me-2 my-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none 
        dark:focus:ring-blue-800"> {{ noProject ? 'Create Project' : 'My Projects' }}
    </button>
</div>

// ProjectManagementApp/src/components/Home.jsx
import { useContext } from 'react';
import noImg from '../assets/no-projects.png';
import { useDispatch } from 'react-redux';
import { projectCreationActions } from '../store';
import { Link, useNavigate } from 'react-router-dom';


export default function Home()
{
  const dispatch = useDispatch();
  const navigate = useNavigate();

  const addNewProject = () => {
    dispatch(projectCreationActions.addNewProject());
    navigate('addProject');
  }

  // const {addNewProject} = useContext(NewProjectContext);
    return (
      <div className="text-center">
        <img
          src={noImg}
          className="w-40 object-contain mx-auto mt-12 mb-4 drop-shadow-md"
        />
        <h3 className="text-gray-500 font-bold text-xl">No Project Selected</h3>
        <h3 className="text-gray-500 text-md leading-10">
          Select a project or get started with a new one
        </h3>
        {/* <Link to = '/addProject'> */}
        <button onClick = {addNewProject} className="text-gray-400 hover:text-white mt-5 px-5 py-3 rounded-md bg-gray-800 hover:bg-black dark:hover:bg-gray-700">
          Create a new project
        </button>
        {/* </Link> */}

      </div>
    );
}
